### ISSUE TITLE
PUT and 201 is not idempotent.

### ISSUE THREAD

**Issue by liuggio** [gimler/symfony-rest-edition#10]
I read  `[PUT] notes/10` like: 
`modify or create resource called 10`,
but if `10` not exists, it will create a new Note with incremental id (different from 10).

The PUT of this implementation, is not idempotent, the state will change for each call of  `[PUT] notes/10` because a new resource will be created.

https://github.com/gimler/symfony-rest-edition/blob/2.3/src/Acme/DemoBundle/Controller/NoteController.php#L227

The solution I see  is make the note array an hash table.

**Comment by lsmith77** [comment]
can you work on a PR?

**Comment by liuggio** [comment]
Yes I think this should be pretty easy :)
