### ISSUE TITLE
bug with location /notes upon creating a new note is not right

### ISSUE THREAD

**Issue by cordoval** [gimler/symfony-rest-edition#21]

**Comment by willdurand** [comment]
what do you mean?

**Comment by cordoval** [comment]
@willdurand this bug was discovered today in the presentation at sunshinephp, basically the Location: X information for when doing a request to create a new note from the command line with http.py returns an output with the Location being /notes, maybe it is intended but @lsmith77 mentioned this was a bug for some reason.

**Comment by willdurand** [comment]
Maybe but it is related to the FOSRestBundle then. It does weird things and call different "view" classes, and I don't really get why. This part of the bundle should probably be refactored.
