### ISSUE TITLE
refactor to no longer use sessions in the example controller

### ISSUE THREAD

**Issue by lsmith77** [gimler/symfony-rest-edition#25]
sqlite is available in all php installs, so it should be safe to use. its awkward to use session in the REST edition (https://github.com/gimler/symfony-rest-edition/blob/2.3/src/Acme/DemoBundle/Controller/NoteController.php#L55), since we should actually disable sessions entirely, since most REST apps should not use sessions.
- [x] refactor NoteController to no longer use sessions
- [x] disable sessions in the app config
- [x] update README.md

**Comment by lsmith77** [comment]
we could even drop Doctrine entirely and instead write into a file

**Comment by realityking** [comment]
Uh, sqlite is not guaranteed to be available in every installation. It has to be enabled at compile time and is in fact an optional module on Debian and Ubuntu.

That said, it's incredibly common, just make sure to require it in composer.json so there are no surprises for users.

**Comment by gimler** [comment]
:-1:  sqlite

We can use cvs files in combination with sys_get_temp_dir what do you think?

**Comment by willdurand** [comment]
why not using Yaml? That is what I ask my students to do first, and it works fine (most of the time).

**Comment by lsmith77** [comment]
fine for me too

**Comment by gimler** [comment]
:+1: for yaml better readable support for nested elements ;)

**Comment by gimler** [comment]
start rewrite note storage from session to temp file see https://github.com/gimler/symfony-rest-edition/tree/remove_session

i use `serialize` and `unserialize` to keep it simple. `Yaml` and `JSON` lost class assocation.

**Comment by lsmith77** [comment]
I created https://github.com/gimler/symfony-rest-edition/pull/30 to make it easier to collaborate on finalizing this.

**Comment by lsmith77** [comment]
opened https://github.com/gimler/symfony-rest-edition/pull/33 to disable sessions
