### ISSUE TITLE
liip/cache-control-bundle is abandoned.

### ISSUE THREAD

**Issue by liuwenchao** [gimler/symfony-rest-edition#29]
```
This package is abandoned and no longer maintained. 
The author suggests using the friendsofsymfony/http-cache-bundle package instead.
```

From https://packagist.org/packages/friendsofsymfony/http-cache-bundle

**Comment by gimler** [comment]
we switch when the stable version is out see also https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/128

**Comment by lsmith77** [comment]
1.0 is out .. so would be great if someone could switch us to this new Bundle
