### ISSUE TITLE
why AsseticBundle???

### ISSUE THREAD

**Issue by desarrolla2** [gimler/symfony-rest-edition#6]
if you are working on rest environment, you don't need assets.

**Comment by lsmith77** [comment]
right now this edition shows how to provide both a REST and HTML UI from the same code base with minimal changes to the official SE. its tricky to try and provide an example for all possible cases. one thing we could do is provide feature branches that remove everything absolutely necessary for a REST API (assetic, twig, doctrine orm ..)
