### ISSUE TITLE
Create a symfony2 distribution for REST

### ISSUE THREAD

**Issue by SimonSimCity** [gimler/symfony-rest-edition#7]
Would it be an idea to create a public available distribution of this, that is specialized for applications having a REST-interface or even also REST-only applications?

This could be decided on whether HTML is a valid response-type ...

If yes, please do not enforce the use of doctrine/orm, because I like to use Couchbase and ElasticSearch to organize my data :)

**Comment by lsmith77** [comment]
no edition will be perfect for every case .. removing the ORM is easy enough though.
